### ISSUE TITLE
Expose ISO8601_REGEX and split into date and datetime regexes

### ISSUE THREAD

**Issue by mlissner** [boxed/iso8601#6]
I'm working on [a json parser](https://pypi.org/project/jsondate3-aware/) that automatically converts ISO-8601 strings into tz-aware datetime objects. I'm planning on using iso8601 for a lot of the logic in it, but one catch is that I need to be able to detect which values in the JSON data are actually iso-8601 dates and which are datetimes. 

This package has most of what I need for that, but needs to be modified in two ways:

1. I need the regex to be split in two. One for dates and one for datetimes.

1. I need the regexes to be public instead of private. 

I could make both of these changes and maintain all current functionality. Would such changes be welcome and could a new version be released quickly with these changes if I made a tidy PR? 

Thanks for the great package. You've done a lot of heavy lifting.

**Comment by boxed** [comment]
I absolutely welcome PRs.

But I don't have a released version of this on pypi, so maybe you're confusing this code with some other library?

**Comment by mlissner** [comment]
Indeed! Sorry about that. It appears the correct one is on...bitbucket???
